/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import db.DbQueries;
import entities.ContractorEntity;
import java.awt.Color;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.swing.BorderFactory;
import tableTemplates.ChoiceContractorsTableTemplate;

/**
 *
 * @author Marek
 */
public class ContractorChoice extends javax.swing.JFrame {
    DbQueries wz = new DbQueries();
    wzListWindow parentFrameWzWindow;
    addProduct parentFrameAddProduct;
    int parentFrameId;
    /**
     * Creates new form ContractorChoice
     */
    public ContractorChoice() {
        getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.GRAY));
        initComponents();
    }
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nipBox = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameBox = new javax.swing.JTextField();
        findContractor = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ContractorTable = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        closeWindow = new javax.swing.JMenuItem();

        setFocusCycleRoot(false);
        setUndecorated(true);

        jLabel1.setText("NIP:");

        jLabel2.setText("Nazwa");

        findContractor.setText("SZUKAJ");
        findContractor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findContractorActionPerformed(evt);
            }
        });

        jButton2.setText("WYBIERZ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ContractorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAZWA", "MIASTO", "KOD POCZTOWY", "ULICA", "NIP"
            }
        ));
        jScrollPane1.setViewportView(ContractorTable);

        jButton3.setText("DODAJ KONTRAHENTA");

        jMenu2.setText("Okno");

        closeWindow.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        closeWindow.setText("Zamknij");
        closeWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeWindowActionPerformed(evt);
            }
        });
        jMenu2.add(closeWindow);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(findContractor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nipBox, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nipBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(nameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(findContractor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeWindowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeWindowActionPerformed
        if(parentFrameId == 1){
            parentFrameWzWindow.enable();
        }
        if(parentFrameId == 2){
            parentFrameAddProduct.enable();
        }
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_closeWindowActionPerformed

    private void findContractorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findContractorActionPerformed
        if (parentFrameId == 1){
            List<ContractorEntity> contractorsList=wz.findContracor(nameBox.getText(), nipBox.getText(), false);
            drawTable(contractorsList);
        }
        if (parentFrameId == 2){
            List<ContractorEntity> contractorsList=wz.findContracor(nameBox.getText(), nipBox.getText(), true);
            drawTable(contractorsList);            
        }
    }//GEN-LAST:event_findContractorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(parentFrameId == 1){
            parentFrameWzWindow.addDocument(Integer.valueOf(ContractorTable.getValueAt(ContractorTable.getSelectedRow(),0).toString()));
            parentFrameWzWindow.toShow = parentFrameWzWindow.wz.getWZDocs();
            parentFrameWzWindow.drawTable(parentFrameWzWindow.toShow);
            parentFrameWzWindow.WZTable.changeSelection(0, 0, false, false);
            parentFrameWzWindow.enable();   
            this.hide();
        }
        if(parentFrameId == 2){
            parentFrameAddProduct.selectedContractorId = (int) ContractorTable.getValueAt(ContractorTable.getSelectedRow(),0);
            parentFrameAddProduct.selectedContractorName = ContractorTable.getValueAt(ContractorTable.getSelectedRow(),1).toString();
            parentFrameAddProduct.enable(); 
            this.hide();    
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    public void drawTable(List<ContractorEntity> contractorsList){
        ContractorTable.getCellSelectionEnabled();
        ChoiceContractorsTableTemplate dtm = new ChoiceContractorsTableTemplate();
        dtm.setRowCount(0);
        ContractorTable.setModel(dtm);
        dtm.setRowCount(contractorsList.size());    
        for(int i = 0; i < contractorsList.size(); i++){
              ContractorTable.getModel().setValueAt(contractorsList.get(i).getId(), i, 0);
              ContractorTable.getModel().setValueAt(contractorsList.get(i).getName() ,i, 1);
              ContractorTable.getModel().setValueAt(contractorsList.get(i).getCity(), i, 2);
              ContractorTable.getModel().setValueAt(contractorsList.get(i).getPostalCode(), i, 3);
              ContractorTable.getModel().setValueAt(contractorsList.get(i).getStreet(), i, 4);
              ContractorTable.getModel().setValueAt(contractorsList.get(i).getNip(), i, 5);
        }  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContractorChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContractorChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContractorChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContractorChoice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContractorChoice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ContractorTable;
    private javax.swing.JMenuItem closeWindow;
    private javax.swing.JButton findContractor;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameBox;
    private javax.swing.JTextField nipBox;
    // End of variables declaration//GEN-END:variables
}
