/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import db.DbQueriesWZ;
import entities.DocEntity;
import entities.DocProductEntity;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import tableTemplates.productTableTemplate;
import tableTemplates.wzTableTemplate;
import utilities.TimeFunctions;
import java.text.DecimalFormat;

/**
 *
 * @author Marek
 */
public class wzList extends javax.swing.JFrame {

    DbQueriesWZ wz = new DbQueriesWZ();
    TimeFunctions time = new TimeFunctions();
    public List<DocEntity> toShow = wz.getWZDocs();
    List<DocProductEntity> productToShow = new ArrayList<>();
    public wzList() {
        initComponents();
        drawTable(toShow);
    }
    public void drawTable(List<DocEntity> docList){
        WZTable.getCellSelectionEnabled();
        wzTableTemplate dtm = new wzTableTemplate();
        dtm.setRowCount(0);
        WZTable.setModel(dtm);
        dtm.setRowCount(docList.size());    
        for(int i = 0; i < docList.size(); i++){
              WZTable.getModel().setValueAt(docList.get(i).getId(), i, 0);
              WZTable.getModel().setValueAt(docList.get(i).getDocNumber(), i, 1);
              WZTable.getModel().setValueAt(docList.get(i).getDocYear(), i, 2);
              WZTable.getModel().setValueAt(docList.get(i).getDocContractorId(), i, 3);
              WZTable.getModel().setValueAt(docList.get(i).getDocContractorName(), i, 4);
              WZTable.getModel().setValueAt(docList.get(i).getDocDate(), i, 5);
              WZTable.getModel().setValueAt(docList.get(i).getDocAcceptDate(), i, 6);
        }  
    }
    private void drawProductTable(List<DocProductEntity> prodList){
        float sumNetto = 0;
        float sumBrutto = 0;
        float netto;
        float vat;
        float number;
        float brutto;
        float sbrutto;
        float snetto;
        productTable.getCellSelectionEnabled();
        productTableTemplate dtm = new productTableTemplate();
        productTable.setModel(dtm);
        DecimalFormat dc = new DecimalFormat("0.00");
        dtm.setRowCount(prodList.size());    
        for(int i = 0; i < prodList.size(); i++){
                netto = prodList.get(i).getPrice();
                vat = (float)prodList.get(i).getVat();
                number = prodList.get(i).getNumber();
                brutto = (float)(netto + (netto*(vat/100)));
                sbrutto = (float)brutto*number;
                sumBrutto += sbrutto;
                snetto = (float)netto*number;
                sumNetto += snetto;
                productTable.getModel().setValueAt(prodList.get(i).getId(), i, 0);
                productTable.getModel().setValueAt(prodList.get(i).getName(), i, 1);
                productTable.getModel().setValueAt(prodList.get(i).getPrice(), i, 2);
                productTable.getModel().setValueAt(dc.format(brutto), i, 3);
                productTable.getModel().setValueAt(prodList.get(i).getUnit(), i, 4);
                productTable.getModel().setValueAt(prodList.get(i).getVat(), i, 5);
                productTable.getModel().setValueAt(prodList.get(i).getNumber(), i, 6);
                productTable.getModel().setValueAt(dc.format(snetto), i, 7);
                productTable.getModel().setValueAt(dc.format(sbrutto), i, 8);
        }  
        nettoLabel.setText(String.valueOf(sumNetto));
        bruttoLabel.setText(String.valueOf(sumBrutto));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        WZTable = new javax.swing.JTable();
        delWZBtt = new javax.swing.JButton();
        newWZBtt = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        productTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        nettoLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        bruttoLabel = new javax.swing.JLabel();
        openWZBtt = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newWZ = new javax.swing.JMenuItem();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);

        WZTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NUMER", "ROK", "ID KLIENTA", "KLIENT", "DATA", "DATA POTWIERDZENIA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(WZTable);

        delWZBtt.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        delWZBtt.setText("-");
        delWZBtt.setMaximumSize(new java.awt.Dimension(40, 40));
        delWZBtt.setMinimumSize(new java.awt.Dimension(40, 40));
        delWZBtt.setPreferredSize(new java.awt.Dimension(40, 40));
        delWZBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delWZBttActionPerformed(evt);
            }
        });

        newWZBtt.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        newWZBtt.setText("+");
        newWZBtt.setMaximumSize(new java.awt.Dimension(40, 40));
        newWZBtt.setMinimumSize(new java.awt.Dimension(40, 40));
        newWZBtt.setPreferredSize(new java.awt.Dimension(40, 40));
        newWZBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWZBttActionPerformed(evt);
            }
        });

        jButton1.setText("Pokaż pozycje dokumentu");
        jButton1.setMaximumSize(new java.awt.Dimension(200, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(200, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(200, 23));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        productTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NAZWA", "CENA NETTO", "CENA BRUTTO", "JEDNOSTKA", "STAWKA VAT", "ILOŚĆ", "SUMA NETTO", "SUMA BRUTTO"
            }
        ));
        jScrollPane2.setViewportView(productTable);

        jLabel1.setText("WARTOŚĆ NETTO:");

        jLabel3.setText("WARTOŚĆ BRUTTO:");

        openWZBtt.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        openWZBtt.setText("o");
        openWZBtt.setMaximumSize(new java.awt.Dimension(40, 40));
        openWZBtt.setMinimumSize(new java.awt.Dimension(40, 40));
        openWZBtt.setPreferredSize(new java.awt.Dimension(40, 40));
        openWZBtt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openWZBttActionPerformed(evt);
            }
        });

        jMenu1.setText("Dokumenty");

        newWZ.setText("Nowy dokument WZ");
        newWZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newWZActionPerformed(evt);
            }
        });
        jMenu1.add(newWZ);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(newWZBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(delWZBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openWZBtt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nettoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bruttoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)))
                .addContainerGap(34, Short.MAX_VALUE))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delWZBtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newWZBtt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(openWZBtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(nettoLabel)
                    .addComponent(jLabel3)
                    .addComponent(bruttoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newWZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWZActionPerformed
        //select * from document_tab where document_type=1 order by document_id desc limit 1; get last document
        DocEntity doc = wz.getLastWZ();
        wz.addDoc(1, time.nowTimestamp(), 0, 0, 0, time.nowYear());
        toShow = wz.getWZDocs();
        drawTable(toShow);
    }//GEN-LAST:event_newWZActionPerformed

    private void newWZBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newWZBttActionPerformed
        DocEntity doc = wz.getLastWZ();
        wz.addDoc(1, time.nowTimestamp(), 0, 0, 0, time.nowYear());
        toShow = wz.getWZDocs();
        drawTable(toShow);
    }//GEN-LAST:event_newWZBttActionPerformed

    private void delWZBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delWZBttActionPerformed
        int selectedDocId = Integer.valueOf(WZTable.getValueAt(WZTable.getSelectedRow(),0).toString());
        Timestamp acceptDate = Timestamp.valueOf(WZTable.getValueAt(WZTable.getSelectedRow(),6).toString());
        long acceptDateLong= time.timestampToLong(acceptDate);
        if (acceptDateLong == 0){
            confirmDeleteDocument confDel = new confirmDeleteDocument();
            confDel.setDocumentID(selectedDocId);
            confDel.setWzL(this);
            confDel.show();
        }
    }//GEN-LAST:event_delWZBttActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int selectedDocId = Integer.valueOf(WZTable.getValueAt(WZTable.getSelectedRow(),0).toString());
        productToShow = wz.getDocProducts(selectedDocId);
        drawProductTable(productToShow);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void openWZBttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openWZBttActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openWZBttActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(wzList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(wzList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(wzList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(wzList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new wzList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable WZTable;
    private javax.swing.JLabel bruttoLabel;
    private javax.swing.JButton delWZBtt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nettoLabel;
    private javax.swing.JMenuItem newWZ;
    private javax.swing.JButton newWZBtt;
    private javax.swing.JButton openWZBtt;
    private javax.swing.JTable productTable;
    // End of variables declaration//GEN-END:variables
}
